language: ruby

rvm:
  - 2.4.2
  - 2.3.5
  - 2.2
  - 2.1

before_script:
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - mv GeoLiteCity.dat data/
