language: ruby

rvm:
  - 2.2
  - 2.0
  - 1.9.3

before_script:
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - mv GeoLiteCity.dat data/
